<?php
session_start();
$error = '';
$success = '';
$saved = false;

var_dump($_SESSION['user']);

$config = $config ?? [
    'mongo_uri' => '',
    'mongo_db' => '',
];

$isLoggedIn = isset($_SESSION['logged_in']) && $_SESSION['logged_in'] === true;
$username = $_SESSION['user']['username'] ?? null;

if ($_SERVER['REMOTE_ADDR'] === '127.0.0.1') {  // consider using env file?
    // Dev environment
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
} else {
    // Production
    error_reporting(0);
    ini_set('display_errors', 0);
}


$cooldown = 5; // 5 seconds rate limit

$configFile = __DIR__ . '/config.php';
$timestampFile = __DIR__ . '/last_saved_time.txt';
$registryFile = __DIR__ . '/config_registry.json';
$configDir = __DIR__ . '/configs';
$redirectToSelector = false;

if (!is_dir($configDir)) {
    mkdir($configDir, 0755, true);
}

if (file_exists($registryFile)) {
    $registry = json_decode(file_get_contents($registryFile), true);
    $activeConfig = $registry['active'] ?? '';

    $activePath = $configDir . '/' . $activeConfig . '.php';
    if ($activeConfig && file_exists($activePath)) {
        $config = include $activePath;
    } else {
        // Active config missing or broken
        header('Location: config-select.php');
        exit;
    }
} else {
    // No registry yet
    header('Location: config-select.php');
    exit;
}

if (!file_exists($registryFile) || empty($registry['active']) || !file_exists($configDir . '/' . $registry['active'] . '.php')) {
    // Optional: log the error
    // Redirect to config setup/selector
    header('Location: config-select.php');
    exit;
}

$config = file_exists($configFile) ? include($configFile) : [
    'mongo_uri' => 'mongodb://localhost:27017',
    'mongo_db' => 'db_example_C137'
];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $mongo_uri = trim(strip_tags($_POST['mongo_uri'] ?? ''));
    $mongo_db = trim(strip_tags($_POST['mongo_db'] ?? ''));
    $config_name_raw = trim($_POST['config_name'] ?? '');
    $overwrite_confirm = isset($_POST['overwrite_confirm']) && $_POST['overwrite_confirm'] === '1';

    // Rate limiting
    $lastSaved = is_file($timestampFile) ? (int)file_get_contents($timestampFile) : 0;
    if (time() - $lastSaved < $cooldown) {
        $_SESSION['config_error'] = "You're saving too quickly. Please wait a few seconds before trying again.";
        header("Location: " . $_SERVER['PHP_SELF']);
        exit;
    }   

        // Sanitize config name
        $config_name = preg_replace('/[^a-zA-Z0-9_-]/', '', $config_name_raw);
        if (empty($config_name)) {
            $config_name = 'config_' . time();
        }
        $configFilePath = "{$configDir}/{$config_name}.php";

        // Validate fields
        if (empty($mongo_uri)) {
            $error = "MongoDB URI is required.";
        } elseif (!preg_match('~^mongodb:\/\/[a-zA-Z0-9:\/._-]+$~', $mongo_uri)) {
            $error = "Invalid MongoDB URI format.";
        } elseif (empty($mongo_db)) {
            $error = "Database name is required.";
        } elseif (!preg_match('/^[a-zA-Z0-9_-]{3,30}$/', $mongo_db)) {
            $error = "Database name must be 3–30 characters with no spaces or special characters.";
        } elseif (file_exists($configFilePath) && !$overwrite_confirm) {
             // Prompt for overwrite confirmation
            $_SESSION['pending_config'] = [
                'mongo_uri' => $mongo_uri,
                'mongo_db' => $mongo_db
            ];
            $_SESSION['config_warning'] = "A configuration already exists. Do you want to overwrite it?";
            header("Location: " . $_SERVER['PHP_SELF']);
            exit;
        } else {
            // Build config PHP file content with metadata
            $created_at = date('Y-m-d H:i:s');

            $configContent = <<<PHP
            <?php
            // Config Name: {$config_name}
            // Created: {$created_at}
            // Generated by Job Fair Dashboard

            return [
                'mongo_uri' => '{$mongo_uri}',
                'mongo_db' => '{$mongo_db}',
            ];
            PHP;

            if (file_exists($timestampFile)) {
                $lastSaved = (int) file_get_contents($timestampFile);
            }

            // Save config file
        if (file_put_contents($configFilePath, $configContent)) {
            file_put_contents($timestampFile, time());

            // Load or initialize registry
            $registry = [];
            if (file_exists($registryFile)) {
                $decoded = json_decode(file_get_contents($registryFile), true);
                $registry = is_array($decoded) ? $decoded : [];
            }

            // Update registry
            $registry['configs'][$config_name] = [
                'filename' => "{$config_name}.php",
                'saved_at' => $created_at
            ];
            $registry['active'] = $config_name;

            file_put_contents($registryFile, json_encode($registry, JSON_PRETTY_PRINT));

            $_SESSION['config_saved'] = "Configuration '{$config_name}' saved successfully!";
            header("Location: " . $_SERVER['PHP_SELF']);
            exit;
        } else {
            $error = "Failed to save configuration. Check file permissions.";
        }
    }
}
    


if (isset($_SESSION['config_saved'])) {
    $success = "Configuration saved successfully!";
    unset($_SESSION['config_saved']);
}

if (isset($_SESSION['config_error'])) {
    $error = $_SESSION['config_error'];
    unset($_SESSION['config_error']);
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>ILU Weekly - Portal</title>
<style>
    /* Base Reset and Layout */
    body {
        margin: 0;
        padding: 0;
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
        background-color:rgb(255, 255, 255);
        color: #222;
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        line-height: 1.6;
    }

    /* Header */
    .site-header {
        background: #fff;
        border-bottom: 1px solid #e0e0e0;
        box-shadow: 0 2px 8px rgba(0,0,0,0.05);
        padding: 0.5rem 2rem;
        position: sticky;
        top: 0;
        z-index: 1000;
    }

    .site-header .logo {
        height: 115px;
        width: 112px;
    }

    .site-header nav a {
        margin-left: 1.5rem;
        text-decoration: none;
        color: #333;
        font-weight: 500;
        transition: color 0.2s ease;
    }

    .site-header nav a:hover {
        color: #0066cc;
    }

    .logo-container,
        nav {
            display: flex;
            align-items: center;
        }

    /* Layout */
    .layout {
        display: flex;
        max-width: 1200px;
        margin: 2rem auto;
        padding: 0 1rem;
        gap: 2rem;
        flex: 1;
    }
    
    /* Nav */
    nav {
        padding: 5px 1rem;
        display: flex;
        align-items: center;
        color: white;
    }

    .nav-links {
        display: flex;
        align-items: center;
    }

    .nav-links a,
    .profile-name {
        color: black;
        text-decoration: none;
        font-size: 1rem;
    }

    .nav-links a {
        text-decoration: none;
        color: #333;
        font-weight: 500;
        padding-bottom: 2px;
        border-bottom: 2px solid transparent;
        transition: 0.2s;
    }
    .nav-links a:hover,
    .nav-links a.active {
        color: #007bff;
        border-bottom: 2px solid #007bff;
    }
    .profile-wrapper {
        position: relative;
        cursor: pointer;
        display: inline-block;
        color: white;
        padding-left: 2rem;
    }

    .dropdown {
        display: none;
        position: absolute;
        top: 100%;
        right: 0;
        background: white;
        color: black;
        min-width: 200px;
        box-shadow: 0 2px 6px rgba(0,0,0,0.2);
        border-radius: 4px;
    }

    .dropdown a {
        display: block;
        padding: 0.5rem 1rem;
        color: black;
        text-decoration: none;
    }

    .dropdown a:hover {
        background-color: #eee;
    }

    .config-link {
        font-size: 16px;
    }


    /* Sidebar */
    .sidebar {
        width: 220px;
        flex-shrink: 0;
        background: #fafafa;
        border: 1px solid #eee;
        padding: 1rem;
        border-radius: 6px;
        position: sticky;
        top: 80px;
        height: fit-content;
    }

    .sidebar h2 {
        font-size: 1.1rem;
        margin-bottom: 1rem;
        color: #0066cc;
    }

    .sidebar ul {
        list-style: none;
        padding: 0;
        margin: 0;
    }

    .sidebar ul li {
        margin-bottom: 0.75rem;
    }

    .sidebar ul li a {
        text-decoration: none;
        color: #0066cc;
        font-weight: 500;
        transition: color 0.2s ease;
    }

    .sidebar ul li a:hover {
        color: #004a99;
    }

    /* Main */
    main {
        flex: 1;
        max-width: 1000px;
        padding: 0 1rem;
    }

    h1 {
        font-size: 2rem;
        font-weight: 700;
        margin-bottom: 0.5rem;
    }

    p.lead {
        font-size: 1.15rem;
        color: #555;
        margin-bottom: 2rem;
    }

    #welcome-message-block {
        color: white;
        margin: 2rem 0;
    }

    #welcome-message-block h1 {
        margin-bottom: 0.5rem;
        font-size: 4rem;
        color: #000;
    }
    /* Section Card */
    section {
        background: #fff;
        border-radius: 6px;
        border: 1px solid #eee;
        padding: 1.5rem;
        margin-bottom: 2rem;
    }

    /* Form */
    label {
        display: block;
        margin-top: 1rem;
        font-weight: 600;
        color: #333;
    }

    input[type="text"] {
        width: 90%;
        padding: 0.5rem 0.75rem;
        margin-top: 0.25rem;
        border: 1px solid #ccc;
        border-radius: 4px;
        font-size: 1rem;
        transition: border 0.2s ease;
    }

    input[type="text"]:focus {
        border-color: #0066cc;
        outline: none;
    }

    button {
        margin-top: 1.2rem;
        padding: 0.6rem 1.2rem;
        background: #0066cc;
        color: #fff;
        border: none;
        border-radius: 4px;
        font-weight: 600;
        font-size: 1rem;
        cursor: pointer;
        transition: background 0.2s ease;
    }

    button:hover {
        background: #0055aa;
    }

    .cancel-button {
        display: inline-block;
        margin-left: 1rem;
        padding: 0.6rem 1.2rem;
        background: #e0e0e0;
        color: #333;
        border-radius: 4px;
        font-weight: 600;
        text-decoration: none;
    }

    .cancel-button:hover {
        background: #d5d5d5;
    }

    /* Code Display */
    pre {
        background: #f4f4f4;
        border-radius: 4px;
        padding: 1rem;
        overflow-x: auto;
        font-size: 0.95rem;
        color: #222;
    }

    /* Messages */
    .success-message {
        margin-top: 1rem;
        color: #2e7d32;
        font-weight: 600;
        text-align: center;
    }

    .error-message {
        margin-top: 1rem;
        color: #c62828;
        font-weight: 600;
        text-align: center;
    }

    .warning-message {
        margin-top: 1rem;
        padding: 1rem;
        background: #fff8e1;
        border: 1px solid #ffcc80;
        color: #ef6c00;
        font-weight: 500;
        border-radius: 4px;
    }

    /* Footer */
    footer {
        text-align: center;
        padding: 1rem;
        font-size: 0.875rem;
        color: #666;
        background: #fafafa;
        border-top: 1px solid #eee;
        margin-top: 3rem;
    }

    /* Developer Docs Block */
    #dev-docs {
        background: #fff;
        padding: 2rem;
        margin: 2rem 0;
        border-left: 4px solid #000;
        border-radius: 4px;
        box-shadow: none;
    }

    #dev-docs h2 {
        color: #000;
        font-size: 1.5rem;
        margin-bottom: 1rem;
    }

    #dev-docs p {
        font-size: 1rem;
        margin-bottom: 1rem;
        color: #333;
    }

    #dev-docs code {
        background: #f0f0f0;
        padding: 2px 6px;
        border-radius: 3px;
        font-family: monospace;
        font-size: 0.95rem;
        color: #c92a2a;
    }

    /* Mobile */
    @media (max-width: 768px) {
        .layout {
            flex-direction: column;
            padding: 1rem;
        }

        .sidebar {
            width: 100%;
            position: relative;
            top: auto;
        }

        main {
            margin: 0;
            padding: 0;
        }

    }

</style>
</head>
<body>

<?php if (isset($_SESSION['message'])): ?>
    <div style="background:#e0ffe0; padding:10px; border:1px solid #8bc34a; color:#2e7d32; margin-bottom:15px;">
        <?= htmlspecialchars($_SESSION['message']) ?>
    </div>
    <?php unset($_SESSION['message']); ?>
<?php endif; ?>

<header class="site-header">
    <nav>
        <div class="logo-container">
            <img class="logo" src="../assets/ilw1.png" alt="Logo">
        </div> 

        <div class="nav-links">
            <a href="index.php"> Home </a>
            <?php if (isset($_SESSION['logged_in']) && $_SESSION['logged_in']): 
                $username = htmlspecialchars($_SESSION['user']['username'] ?? 'User');
            ?>
                <div class="profile-wrapper">
                    <span class="profile-name">👤 <?= htmlspecialchars($username) ?></span>
                    <div class="dropdown">
                        <a href="view_profile.php">View Profile</a>
                        <a href="edit_profile.php">Edit Profile</a>
                        <a href="change_password.php">Change Password</a>
                        <?php if ($_SESSION['role'] === 'superadmin'): ?>
                            <a href="###.php"> ### </a>
                            <a href="###.php"> ### </a>
                        <?php endif; ?>
                        <a href="logout.php" onclick="return confirm('Are you sure you want to log out?')">Logout</a>
                    </div>
                </div>

            <?php else: ?>
                <a href="login.php">Login</a>
                <a href="signup.php">Sign Up</a>
            <?php endif; ?>

            <a href="/site-login/config-select.php">Switch Configuration</a>

        </div>
    </nav>

    <script>
        const profileWrapper = document.querySelector('.profile-wrapper');
        if (profileWrapper) {
            const dropdown = profileWrapper.querySelector('.dropdown');
            profileWrapper.addEventListener('mouseenter', () => dropdown.style.display = 'block');
            profileWrapper.addEventListener('mouseleave', () => dropdown.style.display = 'none');
        }
    </script>
</header>

    <!-- Second Layout (Logged In) --> 
    <?php if (isset($_SESSION['logged_in']) && $_SESSION['logged_in']): 
        $username = htmlspecialchars($_SESSION['user']['username'] ?? 'User');
    ?>

    <div class="layout">
        <main> 
        <div id="welcome-message-block">
            <h1> ILU Weekly </h1>
        </div>

        </main>
    </div>

        
    <!-- Main Layout (Before Logged In) --> 
    <?php else: ?>
    <div class="layout">

    <!-- Sidebar Navigation -->
    <aside class="sidebar">
        <h2>Links</h2>
        <ul>
            <li><a href="#config">MongoDB Configuration</a></li>
            <li><a href="#welcome">Getting Started</a></li>
            <li><a href="#dev-docs">###</a></li>
        </ul>
    </aside>

    <!-- Main Content Area -->
    <main>

    <!-- Welcome Message Section -->
    <div id="welcome-message-block">
        <h1> ILU Weekly </h1>
    </div>

        <section id="config">
            <h2>MongoDB Configuration</h2>
            <p>Set your MongoDB connection details below to get started. This setup will be used by the system to connect to your database.</p>

            <form method="POST" action="" onsubmit="return confirmOverwriteIfNeeded();">
                <label for="config_name">Configuration Name:</label>
                <input type="text" id="config_name" name="config_name" placeholder="__"
                    value="<?= htmlspecialchars($config['config_name'] ?? '') ?>" required>
            
                <label for="mongo_uri">MongoDB Connection URI</label>
                <input type="text" id="mongo_uri" name="mongo_uri" placeholder="mongodb://localhost:27017" 
                    value="<?= htmlspecialchars($config['mongo_uri']) ?>" required>

                <label for="mongo_db">Database Name</label>
                <input type="text" id="mongo_db" name="mongo_db" placeholder="db_example_C137" 
                    value="<?= htmlspecialchars($config['mongo_db']) ?>" required>

                <input type="hidden" id="overwrite_confirm" name="overwrite_confirm" value="0" />

                <button type="submit">Save Configuration</button>
            </form>

            <?php if (!empty($error)): ?>
                <p class="error-message"><?= htmlspecialchars($error) ?></p>
            <?php elseif (!empty($success)): ?>
                <p class="success-message"><?= $success ?></p>
            <?php endif; ?>

            <?php if (isset($_SESSION['config_warning'])): ?>
                <div class="warning-message">
                    <p><?= htmlspecialchars($_SESSION['config_warning']) ?></p>
                    <form method="POST">
                        <input type="hidden" name="mongo_uri" value="<?= htmlspecialchars($_SESSION['pending_config']['mongo_uri']) ?>">
                        <input type="hidden" name="mongo_db" value="<?= htmlspecialchars($_SESSION['pending_config']['mongo_db']) ?>">
                        <input type="hidden" name="overwrite_confirm" value="1">
                        <button type="submit">Yes, Overwrite</button>
                        <a href="<?= $_SERVER['PHP_SELF'] ?>" class="button cancel-button">Cancel</a>
                    </form>
                </div>
            <?php unset($_SESSION['config_warning']); ?>
            <?php endif; ?>
        </section>

        <!-- <section id="welcome">
        <h2> Getting Started</h2>
            <p>Before using this system, you need to connect it to a MongoDB database where user accounts will be stored securely.</p>

            <ol>
                <li>
                    <strong>Where is your database hosted?</strong><br>
                    For local development, it's usually: <code>mongodb://localhost:27017</code>
                </li>
                <li>
                    <strong>What should your database be called?</strong><br>
                    Choose a name like <code>job_portal</code> or <code>users_db</code> — just like naming a folder.
                </li>
            </ol>

            <p>Once you've filled in those details, click <strong>“Save Configuration”</strong> to apply the settings.</p>

            <div style="background:#f0f0f0; padding:10px; border-left:4px solid #2e8b57;">
                After saving, you can head over to the <strong>Sign Up</strong> page to create an account and login in to start using the system!
            </div>
        </section> -->

        <div id="dev-docs">
            <h2> Dev notes </h2>
                
            <p> I'm too lazy to write anything at the moment. Don't mind me. </p>

        </div>
        <?php endif; ?>
    </main>
</div>

<footer>
    &copy; <?= date('Y') ?> ILU Weekly Portal. Powered by PHP & MongoDB.
</footer>
</body>
</html>
